name: Build and Test and Deploy

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

    # With this we can trigger manually
    workflow_dispatch:

jobs:
    npm-test-security:
        runs-on: ubuntu-latest
        steps:
            - name: Chekout of repo
              uses: actions/checkout@v4
            - name: Use Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x
                  cache: "npm"
            - name: Install dependencies
              run: npm install
            - name: Run Integration Tests
              run: npm run test-security

    integration-test:
        runs-on: ubuntu-latest
        needs: npm-test-security
        steps:
            - name: Chekout of repo
              uses: actions/checkout@v4
            - name: Use Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x
                  cache: "npm"
            - name: Install dependencies
              run: npm install
            - name: Run Integration Tests
              run: npm test

    deploy_on_Render:
        runs-on: ubuntu-latest
        # To deploy on production we MUST to push from main, else we should deploy to Test area:
        if: github.ref == 'refs/heads/main'
        #  end execution
        needs: integration-test

        steps:
            - name: Deploy to production
              uses: johnbeynon/render-deploy-action@v0.0.8
              with:
                  service-id: ${{secrets.MY_RENDER_ID}}
                  api-key: ${{secrets.MY_RENDER_API_KEY}}
